### ISSUE TITLE
question(generate_uuid): usage of randomBytes of crypt

### ISSUE THREAD

**Issue by yumetodo** [miniorg/miniverse#1]
`randomBytes` is a function imported from `crypt` in below:

https://github.com/miniorg/miniverse/blob/4f4bedb28c3c9e031d405b77983dd5e411e82b33/lib/generate_uuid.js#L17

https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback

However, this code use `randomBytes` as if it's array.
https://github.com/miniorg/miniverse/blob/4f4bedb28c3c9e031d405b77983dd5e411e82b33/lib/generate_uuid.js#L28

Why we can do such a thing?

**Comment by akihikodaki** [comment]
Fixed with commit dce8ccba2ba404d8ae5f78c793740f6a91330561.
